# Generated by Django 5.2.17 on 2026-09-28 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="zaktualizowano")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=120, unique=True, verbose_name="slug"),
                ),
                (
                    "academic_title",
                    models.CharField(
                        blank=True,
                        help_text="Np. mgr, dr, dr hab.",
                        max_length=40,
                        verbose_name="tytuł",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        choices=[
                            ("psychologist", "Psycholog"),
                            ("psychotherapist", "Psychoterapeuta"),
                            ("psychotherapist_in_training", "Psychoterapeuta w trakcie szkolenia"),
                            ("psychiatrist", "Psychiatra"),
                            ("sexologist", "Seksuolog"),
                            ("coach", "Coach / trener"),
                            ("student", "Student(ka) psychologii"),
                            ("other", "Inny zawód"),
                        ],
                        max_length=40,
                        verbose_name="zawód",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        help_text="Jedno zdanie o sobie, widoczne na liście.",
                        max_length=160,
                        verbose_name="nagłówek",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="o mnie")),
                ("works_online", models.BooleanField(default=False, verbose_name="pracuję online")),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        help_text="Np. polski, angielski.",
                        max_length=200,
                        verbose_name="języki",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="numer prawa wykonywania zawodu / certyfikatu",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="publiczny e-mail"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=32, verbose_name="publiczny telefon"),
                ),
                ("website", models.URLField(blank=True, verbose_name="strona www")),
                (
                    "open_to_work",
                    models.BooleanField(
                        default=False,
                        help_text="Wyróżnia profil dla klinik.",
                        verbose_name="szukam pracy / współpracy",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="profil widoczny publicznie"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="zablokowany przez moderację"),
                ),
                (
                    "visible_to_patients",
                    models.BooleanField(default=False, verbose_name="widoczny dla pacjentów"),
                ),
                (
                    "approaches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specialists",
                        to="core.therapyapproach",
                        verbose_name="nurty",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specialists",
                        to="core.city",
                        verbose_name="miasto",
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="specialists",
                        to="core.specialization",
                        verbose_name="specjalizacje",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "profil specjalisty",
                "verbose_name_plural": "profile specjalistów",
                "ordering": ("-updated_at",),
            },
        ),
    ]
