# Generated by Django 5.2.17 on 2026-09-28 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="nazwa")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="slug")),
                ("is_active", models.BooleanField(default=True, verbose_name="aktywny")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="kolejność"),
                ),
            ],
            options={
                "verbose_name": "specjalizacja",
                "verbose_name_plural": "specjalizacje",
                "ordering": ("sort_order", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TherapyApproach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="nazwa")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="slug")),
                ("is_active", models.BooleanField(default=True, verbose_name="aktywny")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="kolejność"),
                ),
            ],
            options={
                "verbose_name": "nurt terapeutyczny",
                "verbose_name_plural": "nurty terapeutyczne",
                "ordering": ("sort_order", "name"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Voivodeship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True, verbose_name="nazwa")),
                ("slug", models.SlugField(max_length=60, unique=True, verbose_name="slug")),
            ],
            options={
                "verbose_name": "województwo",
                "verbose_name_plural": "województwa",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nazwa")),
                ("slug", models.SlugField(max_length=80, unique=True, verbose_name="slug")),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Pokazywane na stronie głównej.",
                        verbose_name="wyróżnione",
                    ),
                ),
                (
                    "voivodeship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cities",
                        to="core.voivodeship",
                        verbose_name="województwo",
                    ),
                ),
            ],
            options={
                "verbose_name": "miasto",
                "verbose_name_plural": "miasta",
                "ordering": ("name",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "voivodeship"), name="uniq_city_per_voivodeship"
                    )
                ],
            },
        ),
    ]
