# Generated by Django 5.2.17 on 2026-09-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('window_start', models.DateTimeField()),
                ('period_seconds', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'licznik limitu zapytań',
                'verbose_name_plural': 'liczniki limitów zapytań',
                'indexes': [models.Index(fields=['window_start'], name='core_rateli_window__655a84_idx')],
                'constraints': [models.UniqueConstraint(fields=('key', 'window_start', 'period_seconds'), name='uniq_rate_limit_window')],
            },
        ),
    ]
