# Generated by Django 5.2.17 on 2026-09-28 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="zaktualizowano")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("job", "Oferta pracy"),
                            ("internship", "Staż / praktyki"),
                            ("volunteering", "Wolontariat"),
                            ("job_seeking", "Szukam pracy / stażu"),
                            ("room_rental", "Wynajem gabinetu"),
                        ],
                        max_length=20,
                        verbose_name="rodzaj ogłoszenia",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="tytuł")),
                ("slug", models.SlugField(blank=True, max_length=180, verbose_name="slug")),
                ("description", models.TextField(verbose_name="opis")),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="adres / dzielnica"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Na ten adres trafią wiadomości. Domyślnie e-mail autora.",
                        max_length=254,
                        verbose_name="e-mail do kontaktu",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Szkic"),
                            ("published", "Opublikowane"),
                            ("expired", "Wygasłe"),
                            ("archived", "Zarchiwizowane"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="opublikowano"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="wygasa"
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Oflagowane ogłoszenie nie jest widoczne publicznie, niezależnie od statusu.",
                        verbose_name="ukryte przez moderację",
                    ),
                ),
                (
                    "moderation_note",
                    models.TextField(blank=True, verbose_name="notatka moderatora"),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employment_contract", "Umowa o pracę"),
                            ("b2b", "B2B"),
                            ("civil_contract", "Umowa zlecenie / o dzieło"),
                            ("unpaid", "Bezpłatne"),
                            ("other", "Inna"),
                        ],
                        max_length=32,
                        verbose_name="forma zatrudnienia",
                    ),
                ),
                (
                    "work_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on_site", "Stacjonarnie"),
                            ("hybrid", "Hybrydowo"),
                            ("remote", "Zdalnie"),
                        ],
                        max_length=16,
                        verbose_name="tryb pracy",
                    ),
                ),
                (
                    "salary_min",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="wynagrodzenie od (PLN)"
                    ),
                ),
                (
                    "salary_max",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="wynagrodzenie do (PLN)"
                    ),
                ),
                (
                    "salary_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hour", "za godzinę"),
                            ("session", "za sesję"),
                            ("month", "miesięcznie"),
                        ],
                        max_length=16,
                        verbose_name="okres wynagrodzenia",
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="cena (PLN)",
                    ),
                ),
                (
                    "price_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hour", "za godzinę"),
                            ("day", "za dzień"),
                            ("month", "za miesiąc"),
                        ],
                        max_length=16,
                        verbose_name="jednostka ceny",
                    ),
                ),
                (
                    "room_area_m2",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="powierzchnia (m²)"
                    ),
                ),
                (
                    "amenities",
                    models.CharField(
                        blank=True,
                        help_text="Np. fotele, kozetka, klimatyzacja, poczekalnia.",
                        max_length=255,
                        verbose_name="wyposażenie",
                    ),
                ),
                (
                    "availability_description",
                    models.TextField(
                        blank=True,
                        help_text="Np. „wtorki i czwartki po 16:00, soboty cały dzień”.",
                        verbose_name="dostępność – opis",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="core.city",
                        verbose_name="miasto",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zostaw puste, aby dodać ogłoszenie jako osoba prywatna.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="organizations.organization",
                        verbose_name="w imieniu organizacji",
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="listings",
                        to="core.specialization",
                        verbose_name="kategorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "ogłoszenie",
                "verbose_name_plural": "ogłoszenia",
                "ordering": ("-published_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="zaktualizowano")),
                ("sender_email", models.EmailField(max_length=254, verbose_name="e-mail nadawcy")),
                ("message", models.TextField(max_length=5000, verbose_name="wiadomość")),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="e-mail odbiorcy"),
                ),
                ("email_sent", models.BooleanField(default=False, verbose_name="e-mail wysłany")),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_inquiries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="nadawca",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="listings.listing",
                        verbose_name="ogłoszenie",
                    ),
                ),
            ],
            options={
                "verbose_name": "zapytanie",
                "verbose_name_plural": "zapytania",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RoomAvailabilityBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Poniedziałek"),
                            (1, "Wtorek"),
                            (2, "Środa"),
                            (3, "Czwartek"),
                            (4, "Piątek"),
                            (5, "Sobota"),
                            (6, "Niedziela"),
                        ],
                        verbose_name="dzień tygodnia",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="od")),
                ("end_time", models.TimeField(verbose_name="do")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_blocks",
                        to="listings.listing",
                        verbose_name="ogłoszenie",
                    ),
                ),
            ],
            options={
                "verbose_name": "blok dostępności",
                "verbose_name_plural": "bloki dostępności",
                "ordering": ("weekday", "start_time"),
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "kind", "city"], name="listings_li_status_b11e37_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("salary_min__isnull", True),
                    ("salary_max__isnull", True),
                    ("salary_min__lte", models.F("salary_max")),
                    _connector="OR",
                ),
                name="listing_salary_range_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomavailabilityblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="availability_block_end_after_start",
            ),
        ),
    ]
