# Generated by Django 5.2.17 on 2026-09-28 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='imię i nazwisko nadawcy'),
        ),
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zaktualizowano')),
                ('reason', models.CharField(choices=[('spam', 'Spam lub reklama'), ('fraud', 'Podejrzenie oszustwa'), ('inappropriate', 'Treści nieodpowiednie lub nieetyczne'), ('outdated', 'Nieaktualne ogłoszenie'), ('other', 'Inny powód')], max_length=20, verbose_name='powód')),
                ('message', models.TextField(blank=True, max_length=1000, verbose_name='szczegóły')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='rozpatrzone')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.listing', verbose_name='ogłoszenie')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_reports', to=settings.AUTH_USER_MODEL, verbose_name='zgłaszający')),
            ],
            options={
                'verbose_name': 'zgłoszenie ogłoszenia',
                'verbose_name_plural': 'zgłoszenia ogłoszeń',
                'ordering': ('is_resolved', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('listing', 'reporter'), name='uniq_report_per_user')],
            },
        ),
    ]
