# Generated by Django 5.2.17 on 2026-09-28 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="zaktualizowano")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Właściciel"),
                            ("admin", "Administrator"),
                            ("member", "Członek zespołu"),
                        ],
                        default="member",
                        max_length=16,
                        verbose_name="rola",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(blank=True, max_length=120, verbose_name="stanowisko"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "członkostwo",
                "verbose_name_plural": "członkostwa",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="utworzono")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="zaktualizowano")),
                ("name", models.CharField(max_length=200, verbose_name="nazwa")),
                (
                    "slug",
                    models.SlugField(blank=True, max_length=220, unique=True, verbose_name="slug"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("clinic", "Poradnia / klinika"),
                            ("private_practice", "Gabinet prywatny"),
                            ("ngo", "Fundacja / stowarzyszenie"),
                            ("public_institution", "Instytucja publiczna (np. OPS, PPP)"),
                            ("room_provider", "Wynajmujący gabinety"),
                            ("other", "Inna"),
                        ],
                        default="clinic",
                        max_length=32,
                        verbose_name="rodzaj",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="opis")),
                ("address", models.CharField(blank=True, max_length=255, verbose_name="adres")),
                ("website", models.URLField(blank=True, verbose_name="strona www")),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="e-mail kontaktowy"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=32, verbose_name="telefon kontaktowy"),
                ),
                ("tax_id", models.CharField(blank=True, max_length=16, verbose_name="NIP")),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="widoczna publicznie"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Ustawiane przez moderatora po weryfikacji organizacji.",
                        verbose_name="zweryfikowana",
                    ),
                ),
                (
                    "is_blocked",
                    models.BooleanField(
                        default=False,
                        help_text="Zablokowana organizacja i jej ogłoszenia są ukryte.",
                        verbose_name="zablokowana przez moderację",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organizations",
                        to="core.city",
                        verbose_name="miasto",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="organizations",
                        through="organizations.Membership",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="członkowie",
                    ),
                ),
            ],
            options={
                "verbose_name": "organizacja",
                "verbose_name_plural": "organizacje",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="organizations.organization",
                verbose_name="organizacja",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("organization", "user"), name="uniq_membership"
            ),
        ),
    ]
